sudo: required

language: generic

services:
  - docker

script:
  - make install
  - make lint
  - make test-coverage-clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./tests/report/coverage.clover
