sudo: required

language: php

services:
  - docker

env:
  - PHP_CONTAINER=php:5.6-cli
  - PHP_CONTAINER=php:7.0-cli
  - PHP_CONTAINER=diegomarangoni/hhvm:cli

matrix:
  allow_failures:
    - env: PHP_CONTAINER=php:7.0-cli
    - env: PHP_CONTAINER=diegomarangoni/hhvm:cli

before_script:
  - make install

script:
  - make lint
  - make test-coverage-clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./tests/report/coverage.clover
